# Generated by Django 3.2 on 2023-10-05 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_cumulative_stock_volume_and_more'),
        ('product', '0002_auto_20230927_0939'),
    ]

    operations = [
    ]
