# Generated by Django 4.2.4 on 2023-08-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(verbose_name='생년월일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='프로필 업데이트 시기'),
        ),
    ]
