# Generated by Django 4.2.4 on 2023-09-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(verbose_name='비밀번호'),
        ),
    ]
