# Generated by Django 4.2.4 on 2023-10-04 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders_id', models.CharField(max_length=10, verbose_name='주문번호')),
                ('user_id', models.CharField(max_length=40, verbose_name='유저ID')),
                ('orders_date', models.DateTimeField(auto_now_add=True, verbose_name='주문일자')),
                ('orders_status', models.CharField(max_length=20, verbose_name='주문처리상태')),
                ('orders_zipcode', models.CharField(max_length=5, verbose_name='주소(우편번호)')),
                ('orders_address', models.CharField(max_length=50, verbose_name='주소(주소)')),
                ('orders_address_detail', models.CharField(max_length=50, verbose_name='주소(상세주소)')),
                ('reciever', models.CharField(max_length=10, verbose_name='수령자 이름')),
                ('reciever_phone_number', models.CharField(max_length=11, verbose_name='수령자 전화번호')),
                ('reciever_demand', models.CharField(max_length=50, verbose_name='배송시 요청사항')),
                ('orders_update_date', models.DateTimeField(auto_now=True, verbose_name='주문 수정일자')),
                ('payment_demand', models.CharField(max_length=40, verbose_name='결제방식')),
            ],
        ),
    ]
