# Generated by Django 4.2.4 on 2023-10-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders_Deatil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders_detail_id', models.CharField(max_length=10, verbose_name='주문상세번호')),
                ('orders_id', models.CharField(max_length=10, verbose_name='주문번호')),
                ('product_id', models.CharField(max_length=10, verbose_name='제품번호')),
                ('product_name', models.CharField(max_length=10, verbose_name='제품명')),
                ('quantity', models.IntegerField(verbose_name='수량')),
                ('total_price', models.IntegerField(verbose_name='총 가격')),
                ('orders_detail_status', models.CharField(max_length=15, verbose_name='배송처리상태')),
                ('refunable_status', models.BooleanField(default=False, verbose_name='환불가능여부')),
            ],
        ),
    ]
