# Generated by Django 4.2.4 on 2023-10-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_orders_deatil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders_deatil',
            name='product_name',
            field=models.CharField(max_length=20, verbose_name='제품명'),
        ),
    ]
