# Generated by Django 4.2.4 on 2023-10-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_orders_deatil_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='id',
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='장바구니 번호'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orders_id',
            field=models.CharField(auto_created=True, max_length=10, primary_key=True, serialize=False, verbose_name='주문번호'),
        ),
    ]
