# Generated by Django 4.2.4 on 2023-10-10 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_orders_id_alter_cart_cart_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='blupill_quantity',
            new_name='bluepill_quantity',
        ),
    ]
