# Generated by Django 4.2.4 on 2023-10-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_rename_blupill_quantity_cart_bluepill_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='orders_address_extra_detail',
            field=models.CharField(max_length=50, null=True, verbose_name='주소(부가 정보)'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orders_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='주문번호'),
        ),
    ]
