# Generated by Django 4.2.4 on 2023-11-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_remove_orders_orders_address_extra_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orders_id',
            field=models.CharField(auto_created=True, max_length=10, primary_key=True, serialize=False, verbose_name='주문번호'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='reciever',
            field=models.CharField(max_length=10, verbose_name='수령자 이름'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='reciever_phone_number',
            field=models.CharField(max_length=11, verbose_name='수령자 전화번호'),
        ),
    ]
